//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degerlendirme
    {
        public int Degerlendirme_Id { get; set; }
        public string Degerlendirme_Ad { get; set; }
        public string Degerlendirme_Aciklama { get; set; }
        public string Degerlendirme_Tarih { get; set; }
    }
}
