//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeri
    {
        public int Galeri_Id { get; set; }
        public string Galeri_Adi { get; set; }
        public string Galeri_Yeri { get; set; }
        public string Galeri_Tarih { get; set; }
    }
}
