//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int Iletisim_Id { get; set; }
        public string Iletisim_Mail { get; set; }
        public string Iletisim_Tel { get; set; }
    }
}
