//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AydinAydinEntities : DbContext
    {
        public AydinAydinEntities()
            : base("name=AydinAydinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boyut> Boyuts { get; set; }
        public virtual DbSet<Degerlendirme> Degerlendirmes { get; set; }
        public virtual DbSet<Galeri> Galeris { get; set; }
        public virtual DbSet<Hakkinda> Hakkindas { get; set; }
        public virtual DbSet<Iletisim> Iletisims { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Urun> Uruns { get; set; }
        public virtual DbSet<Bilgi> Bilgis { get; set; }
    }
}
