//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int Urun_Id { get; set; }
        public string Urun_Adi { get; set; }
        public string Urun_Aciklama { get; set; }
        public Nullable<int> Kategori_FK { get; set; }
        public Nullable<int> Boyut_FK { get; set; }
    
        public virtual Boyut Boyut { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
