//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Business.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebProje.Business.ServiceReference1.HelloWorldResponse HelloWorld(WebProje.Business.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebProje.Business.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebProje.Business.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name SaatGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaatGetir", ReplyAction="*")]
        WebProje.Business.ServiceReference1.SaatGetirResponse SaatGetir(WebProje.Business.ServiceReference1.SaatGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaatGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<WebProje.Business.ServiceReference1.SaatGetirResponse> SaatGetirAsync(WebProje.Business.ServiceReference1.SaatGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebProje.Business.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebProje.Business.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebProje.Business.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebProje.Business.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaatGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaatGetir", Namespace="http://tempuri.org/", Order=0)]
        public WebProje.Business.ServiceReference1.SaatGetirRequestBody Body;
        
        public SaatGetirRequest() {
        }
        
        public SaatGetirRequest(WebProje.Business.ServiceReference1.SaatGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaatGetirRequestBody {
        
        public SaatGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaatGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaatGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebProje.Business.ServiceReference1.SaatGetirResponseBody Body;
        
        public SaatGetirResponse() {
        }
        
        public SaatGetirResponse(WebProje.Business.ServiceReference1.SaatGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaatGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaatGetirResult;
        
        public SaatGetirResponseBody() {
        }
        
        public SaatGetirResponseBody(string SaatGetirResult) {
            this.SaatGetirResult = SaatGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebProje.Business.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebProje.Business.ServiceReference1.WebServiceSoap>, WebProje.Business.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebProje.Business.ServiceReference1.HelloWorldResponse WebProje.Business.ServiceReference1.WebServiceSoap.HelloWorld(WebProje.Business.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebProje.Business.ServiceReference1.HelloWorldRequest inValue = new WebProje.Business.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebProje.Business.ServiceReference1.HelloWorldRequestBody();
            WebProje.Business.ServiceReference1.HelloWorldResponse retVal = ((WebProje.Business.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebProje.Business.ServiceReference1.HelloWorldResponse> WebProje.Business.ServiceReference1.WebServiceSoap.HelloWorldAsync(WebProje.Business.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebProje.Business.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebProje.Business.ServiceReference1.HelloWorldRequest inValue = new WebProje.Business.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebProje.Business.ServiceReference1.HelloWorldRequestBody();
            return ((WebProje.Business.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebProje.Business.ServiceReference1.SaatGetirResponse WebProje.Business.ServiceReference1.WebServiceSoap.SaatGetir(WebProje.Business.ServiceReference1.SaatGetirRequest request) {
            return base.Channel.SaatGetir(request);
        }
        
        public string SaatGetir() {
            WebProje.Business.ServiceReference1.SaatGetirRequest inValue = new WebProje.Business.ServiceReference1.SaatGetirRequest();
            inValue.Body = new WebProje.Business.ServiceReference1.SaatGetirRequestBody();
            WebProje.Business.ServiceReference1.SaatGetirResponse retVal = ((WebProje.Business.ServiceReference1.WebServiceSoap)(this)).SaatGetir(inValue);
            return retVal.Body.SaatGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebProje.Business.ServiceReference1.SaatGetirResponse> WebProje.Business.ServiceReference1.WebServiceSoap.SaatGetirAsync(WebProje.Business.ServiceReference1.SaatGetirRequest request) {
            return base.Channel.SaatGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebProje.Business.ServiceReference1.SaatGetirResponse> SaatGetirAsync() {
            WebProje.Business.ServiceReference1.SaatGetirRequest inValue = new WebProje.Business.ServiceReference1.SaatGetirRequest();
            inValue.Body = new WebProje.Business.ServiceReference1.SaatGetirRequestBody();
            return ((WebProje.Business.ServiceReference1.WebServiceSoap)(this)).SaatGetirAsync(inValue);
        }
    }
}
